### ISSUE TITLE
Enhancement: better way of calling API commands

### ISSUE THREAD

**Issue by itsayellow** [Paperspace/paperspace-python#51]
With a very simple change to the API functions, they could be much more pythonic.
Right now, you need to call them with a dict 'params' that contains all the API command arguments.

If you simply changed the argument for a API command function definition to use `**params` instead of `params`, you could give arguments to the python function like regular python function keyword arguments.

Like so:
Change (in jobs.py)
```python
def create(params, no_logging=False, extra_files=[]):
```
to
```python
def create(**params, no_logging=False, extra_files=[]):
```

That way, when calling `paperspace.jobs.create()`, you can call it like so:
```python
paperspace.jobs.create(machineType='K80', command='my_command.sh', project='my_project')
```

This is cleaner syntax than having to pass a dict with all of the keywords.

**Comment by itsayellow** [comment]
Also, if you did modify the function definition in this way, you are always free to call it with a dict if you want.
e.g.
```python
def create(**params, no_logging=False, extra_files=[]):
```
and then
```python
params={'machineType':'K80', 'command':'my_command.sh', 'project':'my_project'}
paperspace.jobs.create(**params)
```

**Comment by tallyw00d** [comment]
@itsayellow We'll take this into consideration in future releases.   Thanks for the heads up!
